theme: jekyll-theme-minimal
title: Булат Бариев
description: "Phone: +7(937) 286-34-77|Telegram: @barievbulat|Email: barievbulat@gmail.com|07.07.1986|г. Казань, Татарстан"
logo: "https://barievbulat.github.io/test/tc/593278758.jpeg"
show_downloads: false
